import { useState } from "react";

export default function Benefits() {
  const cards = [
    {
      id: "b1",
      label: "Financial Goals",
      title: "Achieve your Financial Goals",
      body:
        "Achieving one’s financial goals, whether short-term (a vacation next year or buying a car in two years) or long-term (child’s education abroad after 8 years or planning for retirement), requires an understanding of goals and how those goals can be achieved with the right plan. Our approach keeps your financial goals in focus to ensure you are able to achieve them.",
      gradientCss: "linear-gradient(135deg, #FFE7D6 0%, #FFD1B8 100%)",
      shape: (
        <svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
          <circle cx="20" cy="20" r="18" fill="rgba(255,255,255,0.35)" />
          <rect x="60" y="12" width="40" height="40" rx="8" fill="rgba(255,255,255,0.18)" />
        </svg>
      ),
    },
    {
      id: "b2",
      label: "Fund Selection",
      title: "Select the Right Funds",
      body:
        "Selecting the right funds is more than just looking at past performance and picking up the top ones! We follow a rigorous process which is a combination of objective and subjective parameters, such as returns being generated by a fund manager compared to risk being taken and volatility of the returns of a fund.",
      gradientCss: "linear-gradient(135deg, #E6F6FF 0%, #CFEFFF 100%)",
      shape: (
        <svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
          <rect x="6" y="60" width="48" height="48" rx="12" fill="rgba(255,255,255,0.28)" />
          <path d="M80 20 L110 40 L80 60" stroke="rgba(255,255,255,0.28)" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      ),
    },
    {
      id: "b3",
      label: "Technology",
      title: "Experience Technology at its Best",
      body:
        "One of the reasons for the failure of investors to keep up with the investment plan is inordinate time being spent in managing investments. The Nivesh app helps you in tracking your investments on the go in a language that is easy to understand, which has been made possible due to many years of experience of the Nivesh team in building financial technology platforms.",
      gradientCss: "linear-gradient(135deg, #F1E9FF 0%, #E8E0FF 100%)",
      shape: (
        <svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
          <ellipse cx="30" cy="30" rx="22" ry="14" fill="rgba(255,255,255,0.28)" />
          <g opacity="0.6"><path d="M70 80 C85 70 95 90 110 78" stroke="rgba(255,255,255,0.16)" strokeWidth="8" strokeLinecap="round"/></g>
        </svg>
      ),
    },
    {
      id: "b4",
      label: "Expert Guidance",
      title: "Assisted by Qualified AMFI Registered Mutual Fund Distributors",
      body:
        "A mutual fund distributor plays an extremely important role in the entire process by guiding and handholding you throughout your investment journey. We have qualified mutual fund distributors as partners spread all across the country making it a unique proposition that is just right for you!",
      gradientCss: "linear-gradient(135deg, #E9FFF0 0%, #DFFAE8 100%)",
      shape: (
        <svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden>
          <rect x="10" y="10" width="40" height="40" rx="10" fill="rgba(255,255,255,0.22)" />
          <circle cx="86" cy="86" r="18" fill="rgba(255,255,255,0.32)" />
        </svg>
      ),
    },
  ];

  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  return (
    <section className="w-full bg-white rounded-2xl shadow-sm">
      <div className="px-6 md:px-12 py-12">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-2xl md:text-3xl font-extrabold text-slate-900">Benefits of Nivesh</h2>
        </div>

        <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          {cards.map((card, idx) => (
            <article
              key={card.id}
              role="button"
              tabIndex={0}
              onClick={() => setActiveIndex(idx)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") setActiveIndex(idx);
              }}
              className={`relative overflow-hidden rounded-2xl p-6 md:p-8 transition-shadow border border-transparent ${
                activeIndex === idx ? "shadow-xl" : "shadow-lg"
              }`}
              style={{
                background: activeIndex === idx ? card.gradientCss : "#ffffff",
                color: "#000000",
                minHeight: 180,
              }}
            >
              <div className={`absolute -top-6 -right-6 opacity-90 pointer-events-none`}>{card.shape}</div>
              <div className={`rounded-2xl p-0`}>
                <div className={`mb-2 text-sm font-semibold text-slate-700/80`}>{card.label}</div>
                <h3 className={`text-lg font-bold text-slate-900 mb-3`}>{card.title}</h3>
                <p className={`text-sm text-slate-700`}>{card.body}</p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
